project:
  type: book
  execute-dir: project

execute: 
  echo: false
  warning: false
  message: false

book:
  title: "Dissertation Title" 
  author: "Author"
  chapters:
    - index.qmd # uses include and really is pointing to chapters/01-intro.qmd
    - chapters/02-study1.qmd
    - chapters/03-study2.qmd
    - chapters/04-discussion.qmd
  # appendices: 
  #   - appendices/01-renvironment.qmd
  page-navigation: true
  genre: Doctoral dissertation

bibliography: references.bib

csl: csl/apa.csl

crossref: 
  chapters: true
  fig-title: Figure
  tbl-title: Table
  fig-prefix: Figure
  tbl-prefix: Table
  appendix-title: Appendix
  ref-hyperlink: true
  lot-title: 'LIST OF TABLES'
  lof-title: 'LIST OF FIGURES'

format:
  html:
    toc: true
    toc-depth: 4
    toc-location: right
    number-sections: true
    number-depth: 3
    code-fold: true
    theme: cosmo
    fontsize: 0.90em
  docx:
    reference-doc: docx/custom-reference-doc.docx
    toc: true
    toc-depth: 4
    number-sections: true
    number-depth: 2
    highlight-style: github
  pdf:
    biblio-title: References
    toc-title: TABLE OF CONTENTS
    cite-method: biblatex
    biblatexoptions:
      - style=apa
      - backend=biber
    documentclass: report 
    fontsize: 10pt
    template-partials: 
      - "tex/doc-class.tex"
      - "tex/before-body.tex" 
      - "tex/toc.tex"
      - "tex/_titlepage.tex" 
      - "tex/_acknowledgments.tex"
      - "tex/_copyright.tex"
      - "tex/_dedication.tex"
    mainfont: "Times" # replace w/ "Times New Roman" if using Windows, etc.
    toc: true
    toc-depth: 3
    lot: true
    lof: true
    number-sections: TRUE
    format-resources:
      - tex/sfchap.sty
      - tex/sfsection.sty
    include-in-header:
      - text: |
          \usepackage[intoc]{nomencl}
          \usepackage{listings}
          \usepackage{subfig}
          \usepackage{epsfig}
          \usepackage{rotating}
          \usepackage{makeidx}
          
          %% flextable dependencies
          \usepackage{multirow}
          \usepackage{multicol}
          \usepackage{colortbl}
          \usepackage{hhline}
          
          \newlength\Oldarrayrulewidth
          \newlength\Oldtabcolsep
          
          \usepackage[subfigure, titles]{tocloft}
          \usepackage{acronym}
          \usepackage{datetime}
          \usepackage{algorithm}
          \usepackage{algorithmic}
          \usepackage{url}
          \usepackage{makecell}
          \usepackage{titletoc}
          \usepackage{appendix}
          \usepackage[nottoc]{tocbibind}
          \usepackage{sfchap}
          \usepackage{sfsection}
          \setcounter{secnumdepth}{7}
          \setcounter{tocdepth}{7}
          \usepackage{setspace}
          % \usepackage[all]{hypcap}
          
          % Stats table label
          \newcommand{\statslabel}[2]{\multirowcell{#1}[-1.6mm][c]{#2}}
          
          % Below heading rule.
          \newcommand{\otoprule}{\midrule[\heavyrulewidth]}
          
          % Prevent double spaced equations
          \newenvironment{tightequation}{\singlespace\begin{equation}}{\end{equation}}
          
          % Extra junk to pretty up the table of contents
          \setlength{\cftsecnumwidth}{2.8em}
          \setlength{\cftsubsecnumwidth}{3.7em}
          \setlength{\cftsubsubsecnumwidth}{4.6em}
          \setlength{\cftparanumwidth}{5.5em}
          \setlength{\cftsubparanumwidth}{6.5em}
          \setlength{\cfttabnumwidth}{3.5em}
          \setlength{\cftfignumwidth}{3.5em} 
          
          \renewcommand{\chaptermark}[1]{%
          \markboth{\MakeUppercase{%
              \chaptername}\ \thechapter.%
            \ #1}{}}
            
            
          \interfootnotelinepenalty=10000 %prevents the splitting of long footnotes across multiple pages. Use with caution. 

rendering:
  keep-tex: true